// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    DB: D1Database;
    RESEND_KEY: string;
    RESEND_EMAIL_FROM: string;
    RESEND_EMAIL_TO: string;
}
